services:
  transcriber:
    build:
      context: .
      dockerfile: Dockerfile  # Use the Dockerfile in the project root.
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data:rw  # Persistent data directory.
      - ./models:/app/models:rw # Persistent model storage
    environment:
      - ONLINE=True
      - STORAGE_SECRET=${STORAGE_SECRET:?err}  #  From your .env file!
      - DEVICE=cuda
      - HF_AUTH_TOKEN=${HF_AUTH_TOKEN:?err}   #  From your .env file!
      - BATCH_SIZE=${BATCH_SIZE:-4}      # Default to 4 if not set.
      - SUMMARIZATION=${SUMMARIZATION:-False}  #  Default to False.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.transcribo.rule=Host(`${DOMAIN}`)"  # Your domain
#      - "traefik.http.routers.transcribo.entrypoints=websecure"  # Your HTTPS entrypoint
#      - "traefik.http.routers.transcribo.tls=true" # Enable TLS
#      - "traefik.http.services.transcribo.loadbalancer.server.port=8080" # Internal port
#      - "traefik.http.middlewares.transcribo-auth.basicauth.users=transcribo:637eaa4064a2b6dea2d97fd617072835723cf5a2"  #This is commented out!

#networks:
#  traefik_network:
#    external: true